name: build-test
  
on: 
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
        default: '0.0.0'
      cache-build:
        required: false
        type: boolean
        default: false
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .\src
  BUILD_CONFIGURATION: Release

jobs:
  build_test_publish:
    name: Build and run unit tests
    runs-on: windows-latest
    steps:        
    - name: Git configuration
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v4

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet restore

    - name: Show version
      run: echo "Building version ${{ inputs.release-version }}"

    - name: Get number version
      env:
        ReleaseVersion: ${{ inputs.release-version }}
      run: |
        $numberVersion = .\GetNumberVersion -Version ${{env.ReleaseVersion}}
        echo "Setting numberVersion to $numberVersion"
        echo "NUMBER_VERSION=$numberVersion" >> $env:GITHUB_ENV

    - name: Set fileversion on all .NET Framework assemblies and assembly version on the exe
      env:
        ReleaseVersion: ${{ inputs.release-version }}
      run: |
        $sbeFileName = "$env:GITHUB_WORKSPACE\src\ServiceBusExplorer\Properties\AssemblyInfo.cs"
        .\SetVersion -FileName $sbeFileName -PropertyName 'AssemblyVersion' -Version ${{env.NUMBER_VERSION}}
        .\SetVersion -FileName $sbeFileName -PropertyName 'AssemblyFileVersion' -Version ${{env.NUMBER_VERSION}}   
        .\SetVersion -FileName $sbeFileName -PropertyName 'AssemblyInformationalVersion' -VersionString ${{env.ReleaseVersion}}   

        $commonInfoFile = "$env:GITHUB_WORKSPACE\src\Common\Properties\AssemblyInfo.cs"
        .\SetVersion -FileName $commonInfoFile -PropertyName 'AssemblyFileVersion' -Version ${{env.NUMBER_VERSION}}
        .\SetVersion -FileName $commonInfoFile -PropertyName 'AssemblyInformationalVersion' -VersionString ${{env.ReleaseVersion}}   

        $notificationHubsInfoFile = "$env:GITHUB_WORKSPACE\src\NotificationHubs\Properties\AssemblyInfo.cs"
        .\SetVersion -FileName $notificationHubsInfoFile -PropertyName 'AssemblyFileVersion' -Version ${{env.NUMBER_VERSION}}      
        .\SetVersion -FileName $notificationHubsInfoFile -PropertyName 'AssemblyInformationalVersion' -VersionString ${{env.ReleaseVersion}}   

    - name: Build
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} /p:FileVersion=${{env.NUMBER_VERSION}} /p:InformationalVersion=${{inputs.release-version}}

    - name: Run tests
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: dotnet test

    - name: Cache build
      uses: actions/cache@v3.0.11
      if: ${{ inputs.cache-build }}
      with:
        path: src/ServiceBusExplorer/bin/Release
        key: cached-output-${{ github.sha }}
